return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "1.7.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 100,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 4,
  nextobjectid = 9,
  properties = {},
  tilesets = {
    {
      name = "world map",
      firstgid = 1,
      tilewidth = 40,
      tileheight = 40,
      spacing = 0,
      margin = 0,
      columns = 8,
      image = "world.png",
      imagewidth = 320,
      imageheight = 160,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 40,
        height = 40
      },
      properties = {},
      wangsets = {},
      tilecount = 32,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 1,
      name = "Terrain",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt28tuGzEMBVDD6CaIvSiaZdr//8y2gAcQBIni415KGs+Ci6aOHjxDajx2Pm6324czfibGjDlnhNfi8/KgXJtei//xOKmH9xpFrDFiMYodrsdIPjS/x5zfYoGIbA/E2J9Bl1UtZpggxvyswrrelS2yTRDjletumURjtkWmiTSW9lys192rlZmxuskDsG7JROM46ldozwwTr8vhUc6DXHPUA9mjGC6jfazoYemZGefFyiarerDP7lVNyrXdwWu0umTfR61oUo53T8iBtIcZ97Srmcz2aO0h63dbLrNNynF+GIPlocmr5TrL9oiaePZktRuFZX7E+muHDA+2CWKNkgciLB7svbZMNJFpwvYYrZ9hobn2oyYoH69H9FlElkekF432Hu0FKA/PNWOtD4TLMcbzFQwTdB+zekTqWLtGhMkx37MKpMnIhe3Ren5SB6qGW/uM7AsRI1ekxzHW73/xpxp3lJd7EdF+ha4VhkXPJMNDM8fhoPXwrBXZwxAWLZNWz456lP1K2xM9HggTb09je0RMJA9N/so+ZfXw1nQv75a68Zr86ligTBAex/97PLx1EvXwmjwEC4SJ16N1hns9rCYoD4+J9ne8JhaPUUQ8LCZl3u+dn7NMLK/3mKA8Itec1QTtYVmzdX9WE4YH26Tc4736t9dDu2bP3iwmCA/vHqVnLNocsj+H835WpDEZWXg8PHvUPu9axUNaoyVXPY9ebrQe0X1Kz+CscyE/s0Z59OpotNeWw8gjuk/pvbVnzhXro/czab+ShfXzc8teR887rCY7ebRMPP0J+f0rr0fPBOUh5VvKkdbjcRublD1X6mfo78T11iPlpWeC8BjNKdWJxaM0GX1nS/I4TJgelvzUHlmB8IhcIwwP63s363mCrgtP3UTP395cTI/svLEC7SHNVfcUhMnXK2Zcy7M9NC7ZHt+v8PYXhk3WWSPldnRv2fOImiCe+6FrxvLMAzGG936/9fqIifUsz/BB+XqeK1pNeq/3mLAtEOG9bmd7WM+T3S00OVvBQ2uyusWZPDQmO3hYTS6PtUy8HqO8Ri3f1aPOnfVz1bPWh7XvI6NVI1YXKddej5EJy2N2/nvhNbHmfOTRel9SvoblwepdnnyyaiXikmHB9JByZf07pEitIJwOD7YFw8OSfylYJl4PlEU5Tvl3QnWsZNFzsT7/ZfQxlIXkgXaIGljqxeqyggWr1zHqIVozIyPEmR7xOJuF5fxvuZzRg2FRjo+uHVS/ipiwPBg1Uc+BrJ0ze7B607MxF8pkBQ/2fSzSorfmFT08JmyLDI/nSTyQFtI9PNLj2N8u9WExQVho3lOhPXY5PzQmrdcyLVj1cQYPpMVMj3pvqDGZHi0T5Lk92wNpUL8nZHmUJsiz+yweLYtsD5TFrh6t9TGeX2njXT0kA8bz3RkeWpNVLDyfT+3isJPHKt9zaJ0j7+jR6lfv6jHbIWLBPj9mmMy2iLqwz3OGyS4eHhe2B8NkNw+LT4YH2mR3D8kkywNpssOZvoMHyuTywJt4XTRn4uxc7+LxVQTTYweTFTy+i/B4WO/lZ+fcajGrX1nPEqvD5cE18XqsarKyx8gkYnF5xEyOuDzWCu3ad/QYrXd27qWIWqzmoVnv7JwzLVYxsax1dt4zPGa4eNc4O+9ZFlkm0fXNzn2mBdKDtb7Z+c9yQJmx574c1oq/Tu7rRA=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      id = 2,
      name = "Features",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt27ENgDAMBMBUQAWIAth/UixWoLBD7qTvv3ATOW4NAAAAxjZF5siSXYTXGtkie3YRALp2Rq7InV0EAAAAOnFkFwDS2JXVUmVXZi5qqTIXAMB3dtkAADAmbwEAAAAAAAAAGJM7rVrcaQFA//zJBAAAAAAA6Iv9DgAAAAAAf/IAtOQCdA=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "Features",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "origin",
          type = "Point",
          shape = "rectangle",
          x = 1640,
          y = 1600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "floobham:origin",
          type = "Exit",
          shape = "rectangle",
          x = 1720,
          y = 1360,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "bugland:origin",
          type = "Exit",
          shape = "rectangle",
          x = 2000,
          y = 960,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "sign.map",
          type = "Sign",
          shape = "rectangle",
          x = 1600,
          y = 1560,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "sign.floobham",
          type = "Sign",
          shape = "rectangle",
          x = 1720,
          y = 1440,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "sign.floob_castle",
          type = "Sign",
          shape = "rectangle",
          x = 1680,
          y = 1200,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "sign.bugland",
          type = "Sign",
          shape = "rectangle",
          x = 2040,
          y = 1000,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "floob_entry:origin",
          type = "Exit",
          shape = "rectangle",
          x = 1640,
          y = 1160,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
